<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

/**
 * Estructura actual (backup.sql nuevo):
 *
 *   regiones  → id GENERATED ALWAYS AS IDENTITY
 *   provincias → id GENERATED ALWAYS AS IDENTITY, region_id → regiones.id
 *   comuna    → id GENERATED ALWAYS AS IDENTITY, provincia_id → provincias.id
 *              (sin region_id — la relación con región va via provincia)
 */
class RegionProvinciacomunaSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // Desactivar FK checks
        DB::statement('SET session_replication_role = replica;');

        DB::table('comuna')->truncate();
        DB::table('provincias')->truncate();
        DB::table('regiones')->truncate();

        // ════════════════════════════════════════
        //  REGIONES  (16)
        // ════════════════════════════════════════
        DB::table('regiones')->insert([
            ['descripcion' => 'Tarapacá', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Antofagasta', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Atacama', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Coquimbo', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Valparaíso', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Libertador General Bernardo O\'Higgins', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Maule', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Biobío', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Araucanía', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Los Lagos', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Aysén del General Carlos Ibáñez del Campo', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Magallanes y de la Antártica Chilena', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Metropolitana de Santiago', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Los Ríos', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Arica y Parinacota', 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Ñuble', 'created_at' => $now, 'updated_at' => $now],
        ]);

        // IDs generados de regiones (en orden de inserción)
        $regIds = DB::table('regiones')->orderBy('id')->pluck('id')->values();

        // ════════════════════════════════════════
        //  PROVINCIAS  (56)
        // ════════════════════════════════════════
        DB::table('provincias')->insert([
            ['descripcion' => 'Iquique', 'region_id' => $regIds[0], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Tamarugal', 'region_id' => $regIds[0], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Antofagasta', 'region_id' => $regIds[1], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'El Loa', 'region_id' => $regIds[1], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Tocopilla', 'region_id' => $regIds[1], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Copiapó', 'region_id' => $regIds[2], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chañaral', 'region_id' => $regIds[2], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Huasco', 'region_id' => $regIds[2], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Elqui', 'region_id' => $regIds[3], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Choapa', 'region_id' => $regIds[3], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Limarí', 'region_id' => $regIds[3], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Valparaíso', 'region_id' => $regIds[4], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Isla de Pascua', 'region_id' => $regIds[4], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Los Andes', 'region_id' => $regIds[4], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Petorca', 'region_id' => $regIds[4], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quillota', 'region_id' => $regIds[4], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Antonio', 'region_id' => $regIds[4], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Felipe de Aconcagua', 'region_id' => $regIds[4], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Marga Marga', 'region_id' => $regIds[4], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cachapoal', 'region_id' => $regIds[5], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cardenal Caro', 'region_id' => $regIds[5], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Colchagua', 'region_id' => $regIds[5], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Talca', 'region_id' => $regIds[6], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cauquenes', 'region_id' => $regIds[6], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Curicó', 'region_id' => $regIds[6], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Linares', 'region_id' => $regIds[6], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Concepción', 'region_id' => $regIds[7], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Arauco', 'region_id' => $regIds[7], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Biobío', 'region_id' => $regIds[7], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cautín', 'region_id' => $regIds[8], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Malleco', 'region_id' => $regIds[8], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Llanquihue', 'region_id' => $regIds[9], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chiloé', 'region_id' => $regIds[9], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Osorno', 'region_id' => $regIds[9], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Palena', 'region_id' => $regIds[9], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Coyhaique', 'region_id' => $regIds[10], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Aysén', 'region_id' => $regIds[10], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Capitán Prat', 'region_id' => $regIds[10], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'General Carrera', 'region_id' => $regIds[10], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Magallanes', 'region_id' => $regIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Antártica Chilena', 'region_id' => $regIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Tierra del Fuego', 'region_id' => $regIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Última Esperanza', 'region_id' => $regIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Santiago', 'region_id' => $regIds[12], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cordillera', 'region_id' => $regIds[12], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chacabuco', 'region_id' => $regIds[12], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Maipo', 'region_id' => $regIds[12], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Melipilla', 'region_id' => $regIds[12], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Talagante', 'region_id' => $regIds[12], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Valdivia', 'region_id' => $regIds[13], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Ranco', 'region_id' => $regIds[13], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Arica', 'region_id' => $regIds[14], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Parinacota', 'region_id' => $regIds[14], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Diguillín', 'region_id' => $regIds[15], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Itata', 'region_id' => $regIds[15], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Punilla', 'region_id' => $regIds[15], 'created_at' => $now, 'updated_at' => $now],
        ]);

        // IDs generados de provincias (en orden de inserción)
        $provIds = DB::table('provincias')->orderBy('id')->pluck('id')->values();

        // ════════════════════════════════════════
        //  COMUNAS  (346)
        // ════════════════════════════════════════
        DB::table('comuna')->insert([
            ['descripcion' => 'Iquique', 'provincia_id' => $provIds[0], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Alto Hospicio', 'provincia_id' => $provIds[0], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pozo Almonte', 'provincia_id' => $provIds[1], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Camiña', 'provincia_id' => $provIds[1], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Colchane', 'provincia_id' => $provIds[1], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Huara', 'provincia_id' => $provIds[1], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pica', 'provincia_id' => $provIds[1], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Antofagasta', 'provincia_id' => $provIds[2], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Mejillones', 'provincia_id' => $provIds[2], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Sierra Gorda', 'provincia_id' => $provIds[2], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Taltal', 'provincia_id' => $provIds[2], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Calama', 'provincia_id' => $provIds[3], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Ollagüe', 'provincia_id' => $provIds[3], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Pedro de Atacama', 'provincia_id' => $provIds[3], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Tocopilla', 'provincia_id' => $provIds[4], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'María Elena', 'provincia_id' => $provIds[4], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Copiapó', 'provincia_id' => $provIds[5], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Caldera', 'provincia_id' => $provIds[5], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Tierra Amarilla', 'provincia_id' => $provIds[5], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chañaral', 'provincia_id' => $provIds[6], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Diego de Almagro', 'provincia_id' => $provIds[6], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Vallenar', 'provincia_id' => $provIds[7], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Alto del Carmen', 'provincia_id' => $provIds[7], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Freirina', 'provincia_id' => $provIds[7], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Huasco', 'provincia_id' => $provIds[7], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Serena', 'provincia_id' => $provIds[8], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Coquimbo', 'provincia_id' => $provIds[8], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Andacollo', 'provincia_id' => $provIds[8], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Higuera', 'provincia_id' => $provIds[8], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Paiguano', 'provincia_id' => $provIds[8], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Vicuña', 'provincia_id' => $provIds[8], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Illapel', 'provincia_id' => $provIds[9], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Canela', 'provincia_id' => $provIds[9], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Los Vilos', 'provincia_id' => $provIds[9], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Salamanca', 'provincia_id' => $provIds[9], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Ovalle', 'provincia_id' => $provIds[10], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Combarbalá', 'provincia_id' => $provIds[10], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Monte Patria', 'provincia_id' => $provIds[10], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Punitaqui', 'provincia_id' => $provIds[10], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Río Hurtado', 'provincia_id' => $provIds[10], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Valparaíso', 'provincia_id' => $provIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Casablanca', 'provincia_id' => $provIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Concón', 'provincia_id' => $provIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Juan Fernández', 'provincia_id' => $provIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Puchuncaví', 'provincia_id' => $provIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quintero', 'provincia_id' => $provIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Viña del Mar', 'provincia_id' => $provIds[11], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Isla de Pascua', 'provincia_id' => $provIds[12], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Los Andes', 'provincia_id' => $provIds[13], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Calle Larga', 'provincia_id' => $provIds[13], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Rinconada', 'provincia_id' => $provIds[13], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Esteban', 'provincia_id' => $provIds[13], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Ligua', 'provincia_id' => $provIds[14], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cabildo', 'provincia_id' => $provIds[14], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Papudo', 'provincia_id' => $provIds[14], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Petorca', 'provincia_id' => $provIds[14], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Zapallar', 'provincia_id' => $provIds[14], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quillota', 'provincia_id' => $provIds[15], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Calera', 'provincia_id' => $provIds[15], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Hijuelas', 'provincia_id' => $provIds[15], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Cruz', 'provincia_id' => $provIds[15], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Nogales', 'provincia_id' => $provIds[15], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Antonio', 'provincia_id' => $provIds[16], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Algarrobo', 'provincia_id' => $provIds[16], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cartagena', 'provincia_id' => $provIds[16], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'El Quisco', 'provincia_id' => $provIds[16], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'El Tabo', 'provincia_id' => $provIds[16], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Santo Domingo', 'provincia_id' => $provIds[16], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Felipe', 'provincia_id' => $provIds[17], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Catemu', 'provincia_id' => $provIds[17], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Llaillay', 'provincia_id' => $provIds[17], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Panquehue', 'provincia_id' => $provIds[17], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Putaendo', 'provincia_id' => $provIds[17], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Santa María', 'provincia_id' => $provIds[17], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quilpué', 'provincia_id' => $provIds[18], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Limache', 'provincia_id' => $provIds[18], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Olmué', 'provincia_id' => $provIds[18], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Villa Alemana', 'provincia_id' => $provIds[18], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Rancagua', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Codegua', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Coinco', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Coltauco', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Doñihue', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Graneros', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Las Cabras', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Machalí', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Malloa', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Mostazal', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Olivar', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Peumo', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pichidegua', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quinta de Tilcoco', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Rengo', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Requínoa', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Vicente', 'provincia_id' => $provIds[19], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pichilemu', 'provincia_id' => $provIds[20], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Estrella', 'provincia_id' => $provIds[20], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Litueche', 'provincia_id' => $provIds[20], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Marchihue', 'provincia_id' => $provIds[20], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Navidad', 'provincia_id' => $provIds[20], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Paredones', 'provincia_id' => $provIds[20], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Fernando', 'provincia_id' => $provIds[21], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chépica', 'provincia_id' => $provIds[21], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chimbarongo', 'provincia_id' => $provIds[21], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lolol', 'provincia_id' => $provIds[21], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Nancagua', 'provincia_id' => $provIds[21], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Palmilla', 'provincia_id' => $provIds[21], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Peralillo', 'provincia_id' => $provIds[21], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Placilla', 'provincia_id' => $provIds[21], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pumanque', 'provincia_id' => $provIds[21], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Santa Cruz', 'provincia_id' => $provIds[21], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Talca', 'provincia_id' => $provIds[22], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Constitución', 'provincia_id' => $provIds[22], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Curepto', 'provincia_id' => $provIds[22], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Empedrado', 'provincia_id' => $provIds[22], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Maule', 'provincia_id' => $provIds[22], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pelarco', 'provincia_id' => $provIds[22], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pencahue', 'provincia_id' => $provIds[22], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Río Claro', 'provincia_id' => $provIds[22], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Clemente', 'provincia_id' => $provIds[22], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Rafael', 'provincia_id' => $provIds[22], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cauquenes', 'provincia_id' => $provIds[23], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chanco', 'provincia_id' => $provIds[23], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pelluhue', 'provincia_id' => $provIds[23], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Curicó', 'provincia_id' => $provIds[24], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Hualañé', 'provincia_id' => $provIds[24], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Licantén', 'provincia_id' => $provIds[24], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Molina', 'provincia_id' => $provIds[24], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Rauco', 'provincia_id' => $provIds[24], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Romeral', 'provincia_id' => $provIds[24], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Sagrada Familia', 'provincia_id' => $provIds[24], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Teno', 'provincia_id' => $provIds[24], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Vichuquén', 'provincia_id' => $provIds[24], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Linares', 'provincia_id' => $provIds[25], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Colbún', 'provincia_id' => $provIds[25], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Longaví', 'provincia_id' => $provIds[25], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Parral', 'provincia_id' => $provIds[25], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Retiro', 'provincia_id' => $provIds[25], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Javier', 'provincia_id' => $provIds[25], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Villa Alegre', 'provincia_id' => $provIds[25], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Yerbas Buenas', 'provincia_id' => $provIds[25], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Concepción', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Coronel', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chiguayante', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Florida', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Hualqui', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lota', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Penco', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Pedro de la Paz', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Santa Juana', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Talcahuano', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Tomé', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Hualpén', 'provincia_id' => $provIds[26], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lebu', 'provincia_id' => $provIds[27], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Arauco', 'provincia_id' => $provIds[27], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cañete', 'provincia_id' => $provIds[27], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Contulmo', 'provincia_id' => $provIds[27], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Curanilahue', 'provincia_id' => $provIds[27], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Los Alamos', 'provincia_id' => $provIds[27], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Tirúa', 'provincia_id' => $provIds[27], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Los Angeles', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Antuco', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cabrero', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Laja', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Mulchén', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Nacimiento', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Negrete', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quilaco', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quilleco', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Rosendo', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Santa Bárbara', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Tucapel', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Yumbel', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Alto Biobío', 'provincia_id' => $provIds[28], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Temuco', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Carahue', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cunco', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Curarrehue', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Freire', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Galvarino', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Gorbea', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lautaro', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Loncoche', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Melipeuco', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Nueva Imperial', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Padre Las Casas', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Perquenco', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pitrufquén', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pucón', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Saavedra', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Teodoro Schmidt', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Toltén', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Vilcún', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Villarrica', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cholchol', 'provincia_id' => $provIds[29], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Angol', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Collipulli', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Curacautín', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Ercilla', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lonquimay', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Los Sauces', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lumaco', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Purén', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Renaico', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Traiguén', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Victoria', 'provincia_id' => $provIds[30], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Puerto Montt', 'provincia_id' => $provIds[31], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Calbuco', 'provincia_id' => $provIds[31], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cochamó', 'provincia_id' => $provIds[31], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Fresia', 'provincia_id' => $provIds[31], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Frutillar', 'provincia_id' => $provIds[31], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Los Muermos', 'provincia_id' => $provIds[31], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Llanquihue', 'provincia_id' => $provIds[31], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Maullín', 'provincia_id' => $provIds[31], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Puerto Varas', 'provincia_id' => $provIds[31], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Castro', 'provincia_id' => $provIds[32], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Ancud', 'provincia_id' => $provIds[32], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chonchi', 'provincia_id' => $provIds[32], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Curaco de Vélez', 'provincia_id' => $provIds[32], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Dalcahue', 'provincia_id' => $provIds[32], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Puqueldón', 'provincia_id' => $provIds[32], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Queilén', 'provincia_id' => $provIds[32], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quellón', 'provincia_id' => $provIds[32], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quemchi', 'provincia_id' => $provIds[32], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quinchao', 'provincia_id' => $provIds[32], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Osorno', 'provincia_id' => $provIds[33], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Puerto Octay', 'provincia_id' => $provIds[33], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Purranque', 'provincia_id' => $provIds[33], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Puyehue', 'provincia_id' => $provIds[33], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Río Negro', 'provincia_id' => $provIds[33], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Juan de la Costa', 'provincia_id' => $provIds[33], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Pablo', 'provincia_id' => $provIds[33], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chaitén', 'provincia_id' => $provIds[34], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Futaleufú', 'provincia_id' => $provIds[34], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Hualaihué', 'provincia_id' => $provIds[34], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Palena', 'provincia_id' => $provIds[34], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Coyhaique', 'provincia_id' => $provIds[35], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lago Verde', 'provincia_id' => $provIds[35], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Aysén', 'provincia_id' => $provIds[36], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cisnes', 'provincia_id' => $provIds[36], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Guaitecas', 'provincia_id' => $provIds[36], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cochrane', 'provincia_id' => $provIds[37], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'O\'Higgins', 'provincia_id' => $provIds[37], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Tortel', 'provincia_id' => $provIds[37], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chile Chico', 'provincia_id' => $provIds[38], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Río Ibáñez', 'provincia_id' => $provIds[38], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Punta Arenas', 'provincia_id' => $provIds[39], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Laguna Blanca', 'provincia_id' => $provIds[39], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Río Verde', 'provincia_id' => $provIds[39], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Gregorio', 'provincia_id' => $provIds[39], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cabo de Hornos', 'provincia_id' => $provIds[40], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Antártica', 'provincia_id' => $provIds[40], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Porvenir', 'provincia_id' => $provIds[41], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Primavera', 'provincia_id' => $provIds[41], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Timaukel', 'provincia_id' => $provIds[41], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Natales', 'provincia_id' => $provIds[42], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Torres del Paine', 'provincia_id' => $provIds[42], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Santiago', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cerrillos', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cerro Navia', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Conchalí', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'El Bosque', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Estación Central', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Huechuraba', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Independencia', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Cisterna', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Florida', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Granja', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Pintana', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Reina', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Las Condes', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lo Barnechea', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lo Espejo', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lo Prado', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Macul', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Maipú', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Ñuñoa', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pedro Aguirre Cerda', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Peñalolén', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Providencia', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pudahuel', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quilicura', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quinta Normal', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Recoleta', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Renca', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Joaquín', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Miguel', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Ramón', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Vitacura', 'provincia_id' => $provIds[43], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Puente Alto', 'provincia_id' => $provIds[44], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pirque', 'provincia_id' => $provIds[44], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San José de Maipo', 'provincia_id' => $provIds[44], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Colina', 'provincia_id' => $provIds[45], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lampa', 'provincia_id' => $provIds[45], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Tiltil', 'provincia_id' => $provIds[45], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Bernardo', 'provincia_id' => $provIds[46], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Buin', 'provincia_id' => $provIds[46], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Calera de Tango', 'provincia_id' => $provIds[46], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Paine', 'provincia_id' => $provIds[46], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Melipilla', 'provincia_id' => $provIds[47], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Alhué', 'provincia_id' => $provIds[47], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Curacaví', 'provincia_id' => $provIds[47], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'María Pinto', 'provincia_id' => $provIds[47], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Pedro', 'provincia_id' => $provIds[47], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Talagante', 'provincia_id' => $provIds[48], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'El Monte', 'provincia_id' => $provIds[48], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Isla de Maipo', 'provincia_id' => $provIds[48], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Padre Hurtado', 'provincia_id' => $provIds[48], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Peñaflor', 'provincia_id' => $provIds[48], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Valdivia', 'provincia_id' => $provIds[49], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Corral', 'provincia_id' => $provIds[49], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lanco', 'provincia_id' => $provIds[49], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Los Lagos', 'provincia_id' => $provIds[49], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Máfil', 'provincia_id' => $provIds[49], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Mariquina', 'provincia_id' => $provIds[49], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Paillaco', 'provincia_id' => $provIds[49], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Panguipulli', 'provincia_id' => $provIds[49], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'La Unión', 'provincia_id' => $provIds[50], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Futrono', 'provincia_id' => $provIds[50], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Lago Ranco', 'provincia_id' => $provIds[50], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Río Bueno', 'provincia_id' => $provIds[50], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Arica', 'provincia_id' => $provIds[51], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Camarones', 'provincia_id' => $provIds[51], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Putre', 'provincia_id' => $provIds[52], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'General Lagos', 'provincia_id' => $provIds[52], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chillán', 'provincia_id' => $provIds[53], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Bulnes', 'provincia_id' => $provIds[53], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Chillán Viejo', 'provincia_id' => $provIds[53], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'El Carmen', 'provincia_id' => $provIds[53], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pemuco', 'provincia_id' => $provIds[53], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Pinto', 'provincia_id' => $provIds[53], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quillón', 'provincia_id' => $provIds[53], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Ignacio', 'provincia_id' => $provIds[53], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Yungay', 'provincia_id' => $provIds[53], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Quirihue', 'provincia_id' => $provIds[54], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Cobquecura', 'provincia_id' => $provIds[54], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Coelemu', 'provincia_id' => $provIds[54], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Ninhue', 'provincia_id' => $provIds[54], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Portezuelo', 'provincia_id' => $provIds[54], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Ranquil', 'provincia_id' => $provIds[54], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Treguaco', 'provincia_id' => $provIds[54], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Carlos', 'provincia_id' => $provIds[55], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Coihueco', 'provincia_id' => $provIds[55], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'Ñiquén', 'provincia_id' => $provIds[55], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Fabián', 'provincia_id' => $provIds[55], 'created_at' => $now, 'updated_at' => $now],
            ['descripcion' => 'San Nicolás', 'provincia_id' => $provIds[55], 'created_at' => $now, 'updated_at' => $now],
        ]);

        // Reactivar FK checks
        DB::statement('SET session_replication_role = DEFAULT;');
    }
}